SELECT *,
	COUNT(*) AS COUNT,
	RANK() OVER(PARTITION BY GEN, TIER ORDER BY COUNT(*) DESC) AS RANKING
FROM 
	(SELECT GEN, TIER , Ability_1 AS ABILITY FROM pokemon_tiers
	UNION ALL
	SELECT GEN, TIER, Ability_2 FROM pokemon_tiers
	UNION ALL
	SELECT GEN, TIER, Ability_3 FROM pokemon_tiers) AS A
GROUP BY GEN, TIER, ABILITY
HAVING ABILITY != ''
ORDER BY GEN, TIER