SELECT *,
	COUNT(*) AS COUNT,
	RANK() OVER(PARTITION BY GEN, TIER ORDER BY COUNT(*) DESC) AS RANKING
FROM 
	(SELECT GEN, TIER ,Type_1 AS TYPE FROM pokemon_tiers
	UNION ALL
	SELECT GEN, TIER, Type_2 FROM pokemon_tiers) AS A
GROUP BY GEN, TIER, TYPE
HAVING Type != ''
ORDER BY GEN, TIER
