WITH GEN1_2 AS
(SELECT 
			RB_Gen AS ORIGIN,
			RB_Pokemon AS POKEMON FROM gen_rb
	UNION 
	SELECT 
			CASE WHEN a.RB_GEN IS NOT NULL THEN a.RB_GEN ELSE b.GS_GEN END,
            GS_Pokemon AS POKEMON
            FROM gen_gs AS b
    LEFT JOIN gen_rb AS a ON a.RB_POKEMON = b.GS_POKEMON
),
GEN2_3 AS
(SELECT * FROM GEN1_2
	UNION 
SELECT 
			CASE WHEN a.ORIGIN IS NOT NULL THEN a.ORIGIN ELSE b.RS_GEN END,
            RS_Pokemon
            FROM gen_rs AS b
    LEFT JOIN GEN1_2 AS a ON a.POKEMON = b.RS_POKEMON
),
GEN3_4 AS
(SELECT * FROM GEN2_3
	UNION
SELECT 
			CASE WHEN a.ORIGIN IS NOT NULL THEN a.ORIGIN ELSE b.DP_GEN END,
            DP_Pokemon
            FROM gen_dp AS b
    LEFT JOIN GEN2_3 AS a ON a.POKEMON = b.DP_POKEMON
),
GEN4_5 AS
(SELECT * FROM GEN3_4
	UNION
SELECT 
			CASE WHEN a.ORIGIN IS NOT NULL THEN a.ORIGIN ELSE b.BW_GEN END,
            BW_Pokemon
            FROM gen_bw AS b
    LEFT JOIN GEN3_4 AS a ON a.POKEMON = b.BW_POKEMON
),
GEN5_6 AS
(SELECT * FROM GEN4_5
	UNION
SELECT 
			CASE WHEN a.ORIGIN IS NOT NULL THEN a.ORIGIN ELSE b.XY_GEN END,
            XY_Pokemon
            FROM gen_xy AS b
    LEFT JOIN GEN4_5 AS a ON a.POKEMON = b.XY_POKEMON
),
GEN6_7 AS
(SELECT * FROM GEN5_6
	UNION
SELECT 
			CASE WHEN a.ORIGIN IS NOT NULL THEN a.ORIGIN ELSE b.SM_GEN END,
            SM_Pokemon
            FROM gen_sm AS b
    LEFT JOIN GEN5_6 AS a ON a.POKEMON = b.SM_POKEMON
),
GEN7_8 AS
(SELECT * FROM GEN6_7
	UNION
SELECT 
			CASE WHEN a.ORIGIN IS NOT NULL THEN a.ORIGIN ELSE b.SS_GEN END,
            SS_Pokemon
            FROM gen_ss AS b
    LEFT JOIN GEN6_7 AS a ON a.POKEMON = b.SS_POKEMON
),
GEN8_9 AS
(SELECT * FROM GEN7_8
	UNION
SELECT 
			CASE WHEN a.ORIGIN IS NOT NULL THEN a.ORIGIN ELSE b.SV_GEN END,
            SV_Pokemon
            FROM gen_sv AS b
    LEFT JOIN GEN7_8 AS a ON a.POKEMON = b.SV_POKEMON
)

SELECT a.ORIGIN, b.* FROM GEN8_9 AS a
RIGHT JOIN pokemon_tiers AS b ON a.POKEMON = b.POKEMON